# Generated by Django 5.0.4 on 2025-04-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.TextField()),
                ('logo', models.TextField()),
                ('description', models.TextField()),
                ('start_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
