# Generated by Django 5.0.4 on 2025-04-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
