# Generated by Django 5.0.4 on 2025-04-16 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_images', '0002_initial'),
        ('restaurants', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant_image',
            name='restaurant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_image', to='restaurants.restaurant'),
        ),
    ]
