# Generated by Django 5.0.4 on 2025-04-05 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food_images', '0001_initial'),
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodimage',
            name='food',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='foods.foods'),
        ),
    ]
